ALTER TABLE app_user ADD COLUMN IF NOT EXISTS deleted BOOLEAN DEFAULT FALSE;
UPDATE app_user SET deleted = FALSE WHERE deleted IS NULL;
ALTER TABLE app_user ALTER COLUMN deleted SET DEFAULT FALSE;
ALTER TABLE app_user ALTER COLUMN deleted SET NOT NULL;

ALTER TABLE app_user ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMP NULL;
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS deleted_by BIGINT NULL;
ALTER TABLE app_user ADD COLUMN IF NOT EXISTS deletion_reason TEXT NULL;
